name: Update Reservoir Image

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: #allows manual triggering of workflow

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas Pillow

      - name: Run reservoir update script
        run: python scripts/reservoir_update.py

      - name: Commit and push changes
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add -A
          git commit -m "Update Basin8TC.png" || echo "No changes to commit"
          git push origin || echo "No changes to push"
